name: switch maintennce
on:
  schedule:
    - cron: "0 8 7 10 *"
jobs:
  update-liff-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: liff-cli
        run: |
          npm install -g @line/liff-cli
          echo '${{ secrets.CHANNEL_SECRET }}' | liff-cli channel add ${{ vars.CHANNEL_ID }} \
          liff-cli channel use ${{ vars.CHANNEL_ID }} \
          liff-cli app update \
          --liff-id ${{ vars.LIFF_ID }} \
          --endpoint-url "https://example.com"
